import type { BehaviorInsight } from "./behavior-insights";
import type { DriftScan, DriftScanCategory } from "./drift-scan";
import type { InterceptDecision } from "./spend-intercept";

export interface FinancialReportInput {
  executiveSummary: string;
  monthlyOverspendLabel: string;
  scan?: DriftScan;
  behaviorInsights?: Record<string, BehaviorInsight>;
  interceptDecisions?: InterceptDecision[];
  topPatterns?: DriftScanCategory[];
}

export interface FinancialReportInsight {
  label: "Financial pressure" | "Watchlist" | "Steady";
  summary: string;
  sources: string[];
  modelProvider: "ollama" | "unavailable";
  modelName: string;
}

export async function buildFinancialReportInsight(
  input: FinancialReportInput,
  fetcher: typeof fetch = fetch
): Promise<FinancialReportInsight> {
  const topPatterns =
    input.topPatterns ??
    input.scan?.topCategories.filter((category) => category.monthlyOverspendCents > 0).slice(0, 3) ??
    [];
  const sources = buildFinancialReportSources(input, topPatterns);

  try {
    const response = await fetcher("/api/ai/report", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        executiveSummary: input.executiveSummary,
        monthlyOverspendLabel: input.monthlyOverspendLabel,
        topPatterns: topPatterns.map((pattern) => ({
          category: pattern.category,
          oldNormal: pattern.baselineLabel,
          recentNormal: pattern.recentLabel,
          overspend: pattern.monthlyOverspendLabel
        })),
        behaviorInsights: Object.values(input.behaviorInsights ?? {}).map((insight) => ({
          category: insight.category,
          tag: insight.tagLabel,
          answer: insight.answer,
          followUpAnswer: insight.followUpAnswer,
          summary: insight.summary
        })),
        interceptDecisions: (input.interceptDecisions ?? []).map((decision) => ({
          category: decision.category,
          merchant: decision.merchantName,
          decision: decision.decision
        }))
      })
    });

    if (!response.ok) {
      throw new Error("Local report AI is unavailable.");
    }

    const body = await response.json() as { summary?: string; model?: string };

    if (!body.summary?.trim()) {
      throw new Error("Local report AI returned no summary.");
    }

    return {
      label: mapReportLabel(topPatterns.length, input.scan?.monthlyOverspendCents ?? 0),
      summary: cleanFinancialReportSummary(body.summary),
      sources,
      modelProvider: "ollama",
      modelName: body.model ?? "qwen-local"
    };
  } catch {
    return {
      label: mapReportLabel(topPatterns.length, input.scan?.monthlyOverspendCents ?? 0),
      summary: buildUnavailableSummary(input, topPatterns),
      sources,
      modelProvider: "unavailable",
      modelName: "ollama-required"
    };
  }
}

export function describeFinancialReportModel(insight: FinancialReportInsight): string {
  if (insight.modelProvider === "ollama") {
    return "Generated by local Qwen through Ollama using only the scan summary, saved pattern notes, and intercept choices.";
  }

  return "Start Ollama with Qwen locally to generate the detailed financial review.";
}

export function cleanFinancialReportSummary(summary: string): string {
  return summary
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean)
    .filter((line) => !/^one bullet\b/i.test(line))
    .filter((line) => !/^one concrete\b/i.test(line))
    .filter((line) => !/^bullet \d\b/i.test(line))
    .filter((line) => !/^reason:/i.test(line))
    .filter((line) => !/^future scenarios/i.test(line))
    .filter((line) => !/^this review provides/i.test(line))
    .map((line) => line
      .replace(/\bthe user's\b/gi, "your")
      .replace(/\bthe user’s\b/gi, "your")
      .replace(/\bthe user\b/gi, "you")
      .replace(/\bUser Behavior\b/g, "What your note suggests")
      .replace(/\bUser context\b/g, "Your context"))
    .join("\n")
    .trim();
}

export function buildFinancialReportSources(
  input: FinancialReportInput,
  topPatterns =
    input.scan?.topCategories.filter((category) => category.monthlyOverspendCents > 0).slice(0, 3) ??
    []
): string[] {
  const sources = [
    `Drift Score ${input.scan?.scoreLabel ?? "0"}`,
    `Monthly overspend ${input.monthlyOverspendLabel}`
  ];

  for (const pattern of topPatterns) {
    sources.push(
      `${pattern.category}: old normal ${pattern.baselineLabel}, recent normal ${pattern.recentLabel}, monthly overspend ${pattern.monthlyOverspendLabel}`
    );
  }

  for (const insight of Object.values(input.behaviorInsights ?? {})) {
    sources.push(`${insight.category} pattern label: ${insight.tagLabel}`);
  }

  for (const decision of input.interceptDecisions ?? []) {
    sources.push(`${decision.category} intercept: ${decision.merchantName} marked ${decision.decision}`);
  }

  return sources;
}

function mapReportLabel(
  topPatternCount: number,
  monthlyOverspendCents: number
): FinancialReportInsight["label"] {
  if (topPatternCount === 0 || monthlyOverspendCents === 0) {
    return "Steady";
  }

  return monthlyOverspendCents >= 15000 ? "Financial pressure" : "Watchlist";
}

function buildUnavailableSummary(
  input: FinancialReportInput,
  topPatterns: DriftScanCategory[]
): string {
  if (topPatterns.length === 0) {
    return "The scan found no repeated overspending, so there is no recovery target yet. Start Ollama locally to generate a fuller review.";
  }

  const patternText = topPatterns
    .map((pattern) => `${pattern.category} moved from ${pattern.baselineLabel} to ${pattern.recentLabel}`)
    .join("; ");

  return `Local AI is not running yet. The available data still shows ${input.monthlyOverspendLabel}/month in repeated overspend: ${patternText}.`;
}
