import type { BehaviorInsight } from "./behavior-insights";
import type { DriftScan, DriftScanCategory } from "./drift-scan";
import type { InterceptDecision } from "./spend-intercept";

export interface FinancialReportInput {
  executiveSummary: string;
  monthlyOverspendLabel: string;
  scan?: DriftScan;
  behaviorInsights?: Record<string, BehaviorInsight>;
  interceptDecisions?: InterceptDecision[];
  topPatterns?: DriftScanCategory[];
}

export interface FinancialReportInsight {
  label: "Financial pressure" | "Watchlist" | "Steady";
  summary: string;
  sources: string[];
  modelProvider: "ollama" | "unavailable";
  modelName: string;
}

export async function buildFinancialReportInsight(
  input: FinancialReportInput,
  fetcher: typeof fetch = fetch
): Promise<FinancialReportInsight> {
  const topPatterns =
    input.topPatterns ??
    input.scan?.topCategories.filter((category) => category.monthlyOverspendCents > 0).slice(0, 3) ??
    [];
  const sources = buildFinancialReportSources(input, topPatterns);

  try {
    const response = await fetcher("/api/ai/report", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        executiveSummary: input.executiveSummary,
        monthlyOverspendLabel: input.monthlyOverspendLabel,
        topPatterns: topPatterns.map((pattern) => ({
          category: pattern.category,
          oldNormal: pattern.baselineLabel,
          recentNormal: pattern.recentLabel,
          overspend: pattern.monthlyOverspendLabel
        })),
        behaviorInsights: Object.values(input.behaviorInsights ?? {}).map((insight) => ({
          category: insight.category,
          tag: insight.tagLabel,
          answer: insight.answer,
          followUpAnswer: insight.followUpAnswer,
          summary: insight.summary
        })),
        interceptDecisions: (input.interceptDecisions ?? []).map((decision) => ({
          category: decision.category,
          merchant: decision.merchantName,
          decision: decision.decision
        }))
      })
    });

    if (!response.ok) {
      throw new Error("Local report AI is unavailable.");
    }

    const body = await response.json() as { summary?: string; model?: string };

    if (!body.summary?.trim()) {
      throw new Error("Local report AI returned no summary.");
    }

    const cleanedSummary = cleanFinancialReportSummary(body.summary);

    return {
      label: mapReportLabel(topPatterns.length, input.scan?.monthlyOverspendCents ?? 0),
      summary: isLowQualityFinancialReview(cleanedSummary)
        ? buildGroundedFinancialReview(input, topPatterns)
        : cleanedSummary,
      sources,
      modelProvider: "ollama",
      modelName: body.model ?? "qwen-local"
    };
  } catch {
    return {
      label: mapReportLabel(topPatterns.length, input.scan?.monthlyOverspendCents ?? 0),
      summary: buildUnavailableSummary(input, topPatterns),
      sources,
      modelProvider: "unavailable",
      modelName: "ollama-required"
    };
  }
}

export function describeFinancialReportModel(insight: FinancialReportInsight): string {
  if (insight.modelProvider === "ollama") {
    return "Generated by local Qwen through Ollama using only the scan summary, saved pattern notes, and intercept choices.";
  }

  return "Start Ollama with Qwen locally to generate the detailed financial review.";
}

export function cleanFinancialReportSummary(summary: string): string {
  return summary
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean)
    .filter((line) => !/^one bullet\b/i.test(line))
    .filter((line) => !/^one concrete\b/i.test(line))
    .filter((line) => !/^compare old normal\b/i.test(line))
    .filter((line) => !/^connect the behavior\b/i.test(line))
    .filter((line) => !/^explain whether\b/i.test(line))
    .filter((line) => !/^give one\b/i.test(line))
    .filter((line) => !/^bullet \d\b/i.test(line))
    .filter((line) => !/^reason:/i.test(line))
    .filter((line) => !/^future scenarios/i.test(line))
    .filter((line) => !/^this review provides/i.test(line))
    .map((line) => line
      .replace(/\bthe user's\b/gi, "your")
      .replace(/\bthe user’s\b/gi, "your")
      .replace(/\bthe user\b/gi, "you")
      .replace(/\byou changed their\b/gi, "your")
      .replace(/\byour spending habits have\b/gi, "your spending has")
      .replace(/\btheir\b/gi, "your")
      .replace(/\bthey\b/gi, "you")
      .replace(/\bthem\b/gi, "you")
      .replace(/\bUser Behavior\b/g, "What your note suggests")
      .replace(/\bUser context\b/g, "Your context"))
    .join("\n")
    .trim();
}

function isLowQualityFinancialReview(summary: string): boolean {
  return [
    /compare old normal/i,
    /connect the behavior/i,
    /explain whether/i,
    /give one/i,
    /\btheir\b/i,
    /\bthey\b/i,
    /\bdaily\b/i,
    /budget-related issue/i,
    /financial integrity/i,
    /automatic override/i
  ].some((pattern) => pattern.test(summary));
}

function buildGroundedFinancialReview(
  input: FinancialReportInput,
  topPatterns: DriftScanCategory[]
): string {
  if (topPatterns.length === 0) {
    return [
      "### What changed",
      "- Drift did not find repeated overspending in this scan.",
      "### Why it may have happened",
      "- Your recent spending stayed close to the earlier monthly average.",
      "### What to do next",
      "- No reset is needed right now. Keep using Transactions to fix categories if something looks wrong."
    ].join("\n");
  }

  const pattern = topPatterns[0];
  const insight = input.behaviorInsights?.[pattern.category];
  const decisions = (input.interceptDecisions ?? []).filter(
    (decision) => decision.category === pattern.category
  );
  const annualOverspend = formatCurrency(pattern.monthlyOverspendCents * 12);
  const noteText = insight
    ? `Your note says "${insight.answer}"${insight.followUpAnswer ? `, and you added "${insight.followUpAnswer}"` : ""}.`
    : "No Pattern Lab note is saved yet, so the why is still open.";
  const decisionText = decisions.length > 0
    ? buildDecisionText(decisions, pattern.category)
    : "No Intercept choice is saved yet, so the report cannot tell whether the next purchase was intentional.";

  return [
    "### What changed",
    `- ${pattern.category} rose from ${pattern.baselineLabel} to ${pattern.recentLabel} per month, adding ${pattern.monthlyOverspendLabel}/month [${pattern.category} old ${pattern.baselineLabel} recent ${pattern.recentLabel}].`,
    `- If it continues, that is about ${annualOverspend}/year of repeat spending to either keep on purpose or redirect.`,
    "### Why it may have happened",
    `- ${noteText}`,
    `- ${decisionText}`,
    "### What to do next",
    `- This week, choose the one ${pattern.category} purchase that is worth keeping before anything new is bought.`,
    `- For the next 30 days, use your follow-up answer as the default replacement when the same trigger shows up.`,
    `- Keep the pattern if it still feels worth ${pattern.monthlyOverspendLabel}/month; cut the extra repeats if you would rather use that money elsewhere.`
  ].join("\n");
}

function buildDecisionText(decisions: InterceptDecision[], category: string): string {
  const intentionalMerchants = decisions
    .filter((decision) => decision.decision === "intentional")
    .map((decision) => decision.merchantName);
  const dismissedMerchants = decisions
    .filter((decision) => decision.decision === "dismissed")
    .map((decision) => decision.merchantName);

  if (intentionalMerchants.length > 0 && dismissedMerchants.length > 0) {
    return [
      `Your Intercept choices are a mixed signal: ${intentionalMerchants.join(", ")} was worth keeping, while ${dismissedMerchants.join(", ")} was dismissed from the ${category} pattern.`,
      "That means you are separating intentional spending from repeat purchases you do not want to keep."
    ].join(" ");
  }

  if (intentionalMerchants.length > 0) {
    return `${intentionalMerchants.join(", ")} was marked worth keeping, so this looks like a pattern to cap deliberately instead of treating every purchase as a mistake.`;
  }

  return `${dismissedMerchants.join(", ")} was dismissed from the ${category} pattern, which suggests you are learning what should not count as part of the repeat pattern.`;
}

export function buildFinancialReportSources(
  input: FinancialReportInput,
  topPatterns =
    input.scan?.topCategories.filter((category) => category.monthlyOverspendCents > 0).slice(0, 3) ??
    []
): string[] {
  const sources = [
    `Drift Score ${input.scan?.scoreLabel ?? "0"}`,
    `Monthly overspend ${input.monthlyOverspendLabel}`
  ];

  for (const pattern of topPatterns) {
    sources.push(
      `${pattern.category}: old normal ${pattern.baselineLabel}, recent normal ${pattern.recentLabel}, monthly overspend ${pattern.monthlyOverspendLabel}`
    );
  }

  for (const insight of Object.values(input.behaviorInsights ?? {})) {
    sources.push(`${insight.category} pattern label: ${insight.tagLabel}`);
  }

  for (const decision of input.interceptDecisions ?? []) {
    sources.push(`${decision.category} intercept: ${decision.merchantName} marked ${decision.decision}`);
  }

  return sources;
}

function mapReportLabel(
  topPatternCount: number,
  monthlyOverspendCents: number
): FinancialReportInsight["label"] {
  if (topPatternCount === 0 || monthlyOverspendCents === 0) {
    return "Steady";
  }

  return monthlyOverspendCents >= 15000 ? "Financial pressure" : "Watchlist";
}

function buildUnavailableSummary(
  input: FinancialReportInput,
  topPatterns: DriftScanCategory[]
): string {
  if (topPatterns.length === 0) {
    return "The scan found no repeated overspending, so there is no recovery target yet. Start Ollama locally to generate a fuller review.";
  }

  const patternText = topPatterns
    .map((pattern) => `${pattern.category} moved from ${pattern.baselineLabel} to ${pattern.recentLabel}`)
    .join("; ");

  return `Local AI is not running yet. The available data still shows ${input.monthlyOverspendLabel}/month in repeated overspend: ${patternText}.`;
}

function formatCurrency(cents: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0
  }).format(cents / 100);
}
